name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install UV and create virtual environment
        run: |
          python -m pip install uv
          uv venv
          source .venv/bin/activate

      - name: Install project dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run linter
        run: |
          source .venv/bin/activate
          make lint

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >  
            -Dsonar.projectKey=const-1_python-project-50
            -Dsonar.organization=const-1
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.exclusions="**/__pycache__/**,**/.github/**"
